### ISSUE TITLE
License

### ISSUE THREAD

**Issue by larsrinn** [HackSoftware/Django-Styleguide#12]
Thanks for this guide. While I don't agree to everything, there's still a huge bunch of great ideas and concepts in here.

I'd like to copy the code of `utils.py` to one of our projects. But you don't have a license for the project or the file specified, so this is not really possible. Do you want to publish this under an open source license?

**Comment by RadoRado** [comment]
@larsrinn Great suggestion, will add a license at some point this week :+1:

**Comment by RadoRado** [comment]
@larsrinn just added license file :+1:
