### ISSUE TITLE
what is boxes?

### ISSUE THREAD

**Issue by EliaoHame** [HackSoftware/Django-Styleguide#125]
what is the specific meaning of boxes mentioned in the article? can you give an example?

**Comment by RadoRado** [comment]
Hello :wave: 

A "box" is an abstract concept for a place where you keep things, related to a specific concept.

For example, Django, as a framework, gives you multiple boxes:

- Models
- Views
- Forms
- Serializers
- urls
- etc.

And when we are talking about "boxes" in the Django Styleguide, we are saying that we need to define our own "box", for where to keep business logic - the so-called services & selectors.

That's about it.

**Comment by EliaoHame** [comment]
got it. thanks
