### ISSUE TITLE
Error structuring according to RFC7807

### ISSUE THREAD

**Issue by duebbert** [HackSoftware/Django-Styleguide#133]
Have you considered RFC7807 (https://datatracker.ietf.org/doc/html/rfc7807) as a way of structuring errors? I haven't seen it much in the wild but I am always in favour of using standards where possible. Just wondering if you are aware of it and if so what arguments were against using it. Thanks!

Some projects that implemented it:
https://github.com/vapor-ware/fastapi-rfc7807
https://github.com/cbornet/python-httpproblem
https://github.com/dave-shawley/tornado-problem-details

**Comment by RadoRado** [comment]
Hello @duebbert :wave: 

We haven't specifically used RFC7807, but it seems quite reasonable :+1: 

I'll add a mention to it in this particular section - https://github.com/HackSoftware/Django-Styleguide#errors--exception-handling

Thanks for the issue :raised_hands:

**Comment by RadoRado** [comment]
Added a mention here - https://github.com/HackSoftware/Django-Styleguide/commit/231773a58be6a0797e27dcb611d3113ceffa8777

Cheers!

**Comment by RadoRado** [comment]
Closing for now. If you want to add something else, feel free to reopen :raised_hands:

**Comment by duebbert** [comment]
Came across this which might be useful too, although not RFC7807: https://github.com/ghazi-git/drf-standardized-errors
