### ISSUE TITLE
How to setup URLs using this style

### ISSUE THREAD

**Issue by Mokubyow** [HackSoftware/Django-Styleguide#14]
First of all, I think this style/layout of DRF is awesome, its clear and really helps organize a large project!
I'm starting to convert a project of mine to this style and I'm wondering if you ever use other HTTP methods. In the guide, you only use POST when the REST way of doing things for an update would be PATCH or PUT. Is there a reason for that? Furthermore, if you using POST for create and update what do your URLs end up looking like? Following your style guide you can't have URLs like this:

```
path("products",  ProductCreate.as_view()) 
path("products",  ProductList.as_view()) 
path("products/<int:product_id>",  ProductUpdate.as_view()) 
path("products/<int:product_id>",  ProductDelete.as_view())
``` 

They would have to look more like this:

```
path("products/create",  ProductCreate.as_view()) 
path("products",  ProductList.as_view()) 
path("products/<int:product_id>/update",  ProductUpdate.as_view()) 
path("products/<int:product_id>"/delete,  ProductDelete.as_view()) 
```

I haven't tried using the other HTTP method and this style so maybe you can have overlapping urls that way? Do you have any examples for all CURD operations or suggestions on how you structure your URLs?

**Comment by jim-pansn** [comment]
I was wondering the exact same thing. Did you figure something out?

**Comment by RadoRado** [comment]
First - sorry for answering that late. I'm really bad at following notifications for something. Second - that's a great question & something we are still discussing inside HackSoft.

We usually build CRUD URLs like that:

```
POST /entity/create -> EntityCreateApi
POST /entity/<entityId>/update -> EntityUpdateApi
POST /entity/<entityId>/delete -> EntityDeleteApi
GET /entity -> EntityListApi
GET /entity/<entityId> -> EntityDetailApi
```

I can agree that's too verbose, but it lets you keep the APIs separate, which is a great win to have.

If you want to avoid the `/create`, `/update`, etc. URLs, but still preserve the 4 different APIs, I'll probably do something like that - implement a small abstraction - something called an "API Gateway":

```python
class UserGatewayApi(GatewayApi):
    get = (UserListApi, UserDetailApi)
    post = (UserCreateApi, UserUpdateApi)
    delete = UserDeleteApi
```

And this will follow a simple rule:

* If you get a `GET` request, without any parameter, use the first item (list api)
* If you get a `GET` request, with a specific parameter, use the second item (detail api)
* Same things for `POST`

Then your URLs can look like this:

```
urlpatterns = [
    path('users', UserGatewayApi.as_view()),
    path('users/<int:user_id>', UserGatewayApi.as_view()),
]
```

Now, the interface of that gateway can be improved.

I think I'll draft an example, just to see where things can break, and post it here :+1:

**Comment by Mokubyow** [comment]
@RadoRado Thank you for responding! I like the API Gateway solution. Can you please ping me once you have a working example of this?

**Comment by DrBenton** [comment]
@Mokubyow Something like this does the trick - even though that's probably not the most elegant and performant way to do it ^_^

```python
class UserGatewayApi(rest_viewsets.GenericViewSet):
    _list_view = UserListApi()
    _create_view = UserCreateApi()

    def list(self, request):
        return self._list_view.get(request)

    def create(self, request):
        return self._create_view.post(request)
```

**Comment by RadoRado** [comment]
@Mokubyow @DrBenton Actually, something like this would do :+1: 

I've added a PR to describe URLs - #28 

After some time, we haven't seen any issues with that approach in our projects, that's why we are going to recommend it in the styleguide.

As for the API gateway, if anyone likes to PR a suggestion about that, we'd be more than happy to review & include it.

But I haven't seen a real benefit of that yet.

Cheers!

**Comment by RadoRado** [comment]
Folks, I'll be closing this as #28 has been merged. Feel free to ping me again, if any further explanation is needed :raised_hands:

**Comment by idoob** [comment]
Hi @RadoRado , 

I have the same question regarding the use of POST instead of PUT/PATCH. Mokubyow asked this in his original post but it wasn't addressed. Can you explain why the guide suggests using POST for updates instead of PUT/PATCH? I'm curious how you are handling full and partial updates of a resource. 

Thanks!
