### ISSUE TITLE
maybe link is error？

### ISSUE THREAD

**Issue by DaoSYi** [HackSoftware/Django-Styleguide#140]
The implementation of inline_serializer can be found [here](https://github.com/HackSoftware/Styleguide-Example/blob/master/styleguide_example/common/utils.py#L34), in the [Styleguide-Example](https://github.com/HackSoftware/Styleguide-Example) repo.

https://github.com/HackSoftware/Styleguide-Example/blob/master/styleguide_example/common/utils.py#L34 ----> https://github.com/HackSoftware/Django-Styleguide-Example/blob/master/styleguide_example/api/utils.py#L8

**Comment by RadoRado** [comment]
@DaoSYi Thanks for noticing this!

And sorry for the late response.

I've just pushed a fix for that -  https://github.com/HackSoftware/Django-Styleguide/commit/d7d50a9d93bfef4953ba17c3da28ff20429ec2d3
