### ISSUE TITLE
Why not use APIException

### ISSUE THREAD

**Issue by HomaDev** [HackSoftware/Django-Styleguide#146]
Hello @RadoRado, hope you are doing well!
There is a class `rest_framework.exceptions.APIException` and it looks like a grate tool to use. 
You can specify all needed information in it, or use it as a base class for custom exception classes. 
Why don't you use it?

**Comment by RadoRado** [comment]
@HomaDev Hello :wave: 

It really depends on what kind of base exception you'd like to have.

Again, we are trying to split things in 2 base categories:

1. Framework-related stuff. If I want to have an exception, that's related to the framework (Django, Django Rest Framework) - for example, something related to how the API behaves, certainly, `APIException` is a great base class
2. Business / domain related stuff. For me, it always feels strange to raise an `APIException` (or something based on that), from a location in my codebase / project, that has no actual knowledge about that's being used by an API.

From our experience so far, what we've described here - https://github.com/HackSoftware/Django-Styleguide?tab=readme-ov-file#errors--exception-handling - works really well.

Cheers!
