### ISSUE TITLE
Business logic and test factories

### ISSUE THREAD

**Issue by hgylfason** [HackSoftware/Django-Styleguide#147]
_Do you have a reliable way to make sure test factories cover important business logic?_ To explain what I mean, let's look at the `create_user` service from the README. It doesn't just create a user; it also sets up a profile and sends a confirmation email. But a standard User model test factory only creates the user, without the extra steps.

_Would you have any tips or examples from your projects on how to handle this? Any insights would be very helpful._

**Comment by RadoRado** [comment]
@hgylfason I'll close this for now. Feel free to reopen, if you need additional info or if you have other questions.

Cheers!
