### ISSUE TITLE
Why Overloaded POST over PUT/PATCH/DELETE?

### ISSUE THREAD

**Issue by frontendschmacktend** [HackSoftware/Django-Styleguide#148]
As a startup founder halfway through building my first fully productionized Django API, I just want to say this might be the single most useful Django-related document on the internet right now, major kudos for putting this together from your battle scars over the years. I've read through all the rebuttals to this styleguide and they all miss the point: simplicity scales. Because of this, we are very careful to make sure we understand why you make certain choices before deviating from them when they don't make sense to us. 

- The biggest one is the format you chose for your endpoints, to create many many endpoints that are only either GET or POST endpoints vs keeping the number of endpoints low and having multiple methods (like GET/POST/PUT/PATCH/DELETE) per endpoint. Here are a few reasons we are choosing not to follow you on this and have the methods (still each with its own serializer) under one view, please help us understand your reasoning on this topic:
      -  We use a few packages that generate endpoints, auth through djoser for example, that follow the conventional multiple-method-per-endpoint way. If we were to follow your one-method-per-endpoint way, we would have a weird API format where some endpoints work one way and some endpoints work the other way. Changing the way these packages generate their endpoints is non-trivial and not where we want to spend our time.
      - The simplicity we get dealing with one view per endpoint is balanced out by the drawback of having to deal with 1000's of endpoints vs 100's on the frontend. We think we are still able to keep things simple by keeping most logic in our services/selectors layer and keeping one view per endpoint with multiple methods (and a serializer for each method) inside the view.
      - We anticipate you choose GET/POST methods because you often work with large customers where you can't control their networking, and from what I heard there are sometimes firewalls/legacy systems that don't like PUT/PATCH/DELETE methods for legacy security reasons. We control our own stack so don't see this as a priority for now.

- The other one is your preference of Serializers over ModelSerializers. What is the benefit of having to manually change a field across many serializers vs just inheriting from the model where you can change it once and it changes everywhere? This way you know each API is going to read/write this field to the database in the right format.

- As an aside, any best practices you have around automating drf-spectacular to generate OpenAPI specifications in SwaggerUI would be appreciated. For example we're working on adding example request/response JSON bodies to each endpoint so our frontend team already have a full example working when getting started.

**Comment by HomaDev** [comment]
@frontendschmacktend Using only Post and Get really suspicious, and I want to know why to. 
But did I understand correctly, that you want to include all methods for one model under one ApiView instead of separating on different ApiView for each method?

**Comment by frontendschmacktend** [comment]
Yes that's correct, any thoughts on the pros/cons of that if we still keep each method's code minimal in the views.py file as is in the styleguide?

**Comment by HomaDev** [comment]
@frontendschmacktend

**Comment by HomaDev** [comment]
But really @RadoRado, why should't we use all needed methods?
post on create, patch on update, delete on delete?

**Comment by RadoRado** [comment]
@frontendschmacktend / @HomaDev I just saw this issue :see_no_evil:

Reading everything & answering accordingly.

**Comment by RadoRado** [comment]
> The biggest one is the format you chose for your endpoints, to create many many endpoints that are only either GET or POST endpoints vs keeping the number of endpoints low and having multiple methods (like GET/POST/PUT/PATCH/DELETE) per endpoint. Here are a few reasons we are choosing not to follow you on this and have the methods (still each with its own serializer) under one view, please help us understand your reasoning on this topic:

I think this is most often the case with folks checking the styleguide.

we have no problems with either approach.

Perhaps, our single biggest reason to stick to the "1 API per action per endpoint" is because it's simple - the API is doing 1 thing.

> The other one is your preference of Serializers over ModelSerializers. What is the benefit of having to manually change a field across many serializers vs just inheriting from the model where you can change it once and it changes everywhere? This way you know each API is going to read/write this field to the database in the right format.

If you find `ModelSerializer` more convenient - simply stick to it!

The way we reason about serializers is that they define the input / output interface of an API, and we don't necessarily want to have that 1:1 relation with a model.

Sometimes - it's a model. Other times - it's something else. So in order to keep a clear distinction - we prefer the pure `Serializer` class.

> As an aside, any best practices you have around automating drf-spectacular to generate OpenAPI specifications in SwaggerUI would be appreciated. For example we're working on adding example request/response JSON bodies to each endpoint so our frontend team already have a full example working when getting started.

I think this issues gives the best approach - https://github.com/HackSoftware/Django-Styleguide/issues/105

**Comment by RadoRado** [comment]
@HomaDev About the HTTP verbs <-> APIs - it's a matter of taste. As long as you keep things consistent - use whatever makes sense to you.

For me, personally, unless I'm building an API that needs to be RESTful and consumed by unknown clients - I tend to stick to GET / POST, since this covers the "read data" vs. "write data" paradigm.

**Comment by RadoRado** [comment]
I'm closing this issue for now. Feel free to reopen or simply open a new one :raised_hands:
