### ISSUE TITLE
People can't use labels 

### ISSUE THREAD

**Issue by HomaDev** [HackSoftware/Django-Styleguide#149]
Does it intend that people can't use labels on issues?

**Comment by RadoRado** [comment]
@HomaDev Not really sure about that. Must be some kind of a permission - will check it :+1: 

Definitely not intentional.

**Comment by RadoRado** [comment]
Yep, it's permission-based. You need actual permissions to the repository, in order to add labels.

**Comment by HomaDev** [comment]
> Yep, it's permission-based. You need actual permissions to the repository, in order to add labels.

But you probably can change it?

**Comment by HomaDev** [comment]
If every user will be able to attach labels, it will be much easier to navigate

**Comment by RadoRado** [comment]
@HomaDev My suggestion is to keep things simple.

There are usually 3-5 issues per few months, so no need to complicate things with labels.

Closing this for now.

Cheers!
