### ISSUE TITLE
Third party APIs

### ISSUE THREAD

**Issue by elias-ebrahimpour** [HackSoftware/Django-Styleguide#153]
Hello and greetings,

I have a question for which I did not find a suitable answer.
In most of my projects, we had some third-party services or APIs to call (with `requests` or `http.client`).
Where do I have to put them? In the services file/folder or selectors, or anywhere else?

Finally, thanks for this good style guide.

**Comment by RadoRado** [comment]
@elias-ebrahimpour Hello :wave: 

Perhaps, the best way to illustrate our approach is within our Styleguide Example - https://github.com/HackSoftware/Django-Styleguide-Example/blob/master/styleguide_example/integrations/aws/client.py

We tend to write "clients" for everything that goes outside the system, and then, interact with those clients in the service layer and/or task layer, whenever is necessary.

Yet, the most important thing for those clients is to define an interface for interaction with something outside of our current & existing system.

Let me know if this answers your questions and you need me to put few more sentences together.

Cheers!

**Comment by elias-ebrahimpour** [comment]
@RadoRado Thank you for your response and time.
I've gotten my answer but if you want to explain more about this issue, I'm all ears.

Cheers!

**Comment by devmitrandir** [comment]
@RadoRado Hi!

For example, I have 2 applications: “integrations” and “blog”.

I need to fetch data from a third party API once a day and store it in a database.
My models are in the "blog" application.

In which application is it better to add logic?

I think I need to add the client in "integrations" and use it in "blog/services.py". And call this service from a celery task ("blog/tasks.py").

**Comment by devmitrandir** [comment]
@RadoRado 
Thank you very much!
