### ISSUE TITLE
Going round in circles

### ISSUE THREAD

**Issue by kevpio** [HackSoftware/Django-Styleguide#156]
Hi, 

I'm new to Django but not new to creating APIs and microservices using other frameworks like flask and graphql. 
I'm trying to create my own project to both learn Django and because I want to create an app for something.

I've gone through the drf tutorials but wasn't happy about where I was supposed to put business logic when using the generics and after some searching found this style guide. It all seems ok with a quick read through but when I try and actually put it into practice I can't seem to find in this guide a clear pattern for how to do a crud API. You flit from a User to File to Course (course is not represented in your the actual code here). All I want is to see how you would structure the full CRUD api for something including the model including Create, READ, Update and Delete.

Sorry if my tone seems a little off, but I'm just frustrated, the ideas you have seem good and I want to adopt them but this guide is not helping me to put it into practice.

**Comment by bhatiavivek** [comment]
You might be in the wrong place on github. [Django Rest Framework](https://github.com/encode/django-rest-framework) has everything you need. The docs are excellent and the LLMs are also pretty good at it.

**Comment by RadoRado** [comment]
@kevpio Hello :wave: 

Sorry for replying late.

If you give me some more context, I'd be able to help you better.

Generally speaking, if you want to expose an API from Django, you can use either DRF or django-ninja (the popular choices)

This styleguide mentions how to approach that when you have an API (which is basically the same with views)

As for example, we have plenty of code here - https://github.com/HackSoftware/Django-Styleguide-Example

Cheers!

**Comment by RadoRado** [comment]
Also, feel free to reopen, if needed

**Comment by kevpio** [comment]
Hi @RadoRado,
Thanks for your comment. I'm trying to write my own API driven application. I want to write it in Django, but I didn't want to be hemmed in my using the DRF generics or viewsets which spreads the business logic all over the place. I found this style guide which seemed to answer that but the examples in your code don't show a simple pattern of how to do that.
What I hoped to see was an example API view class for each element of a CRUD API, including serializers, selectors, filters, etc. But your styleguide and its code doesn't seem to have that. I put most of this as a first message in this issue, and the first guy said I shouldn't be reading the styleguide (so why have it?) and go look at DRF docs - as if I haven't been doing that - but those docs steer you into generics and viewsets which is exactly what I was trying to avoid. His second suggestion was let LLMs write it for me, which would teach me precisely zero. Given that was the only response I closed the issue.

**Comment by RadoRado** [comment]
@kevpio Hello :wave: 

I'm only now seeing the notification for that, so I'm sorry for the delayed response :crying_cat_face: 

For working examples, I'd recommend:

1. This section of the styleguide - https://github.com/HackSoftware/Django-Styleguide?tab=readme-ov-file#apis--serializers
2. Additionally, I've just added a very simple full CRUD example in the Django Styleguide Example project - https://github.com/HackSoftware/Django-Styleguide-Example/blob/master/styleguide_example/users/apis.py

Let me know if you need anything else (I'm now watching notifications and I sweep thru the opensource repos every Wednesday)
