### ISSUE TITLE
Browsable API

### ISSUE THREAD

**Issue by dakzh** [HackSoftware/Django-Styleguide#16]
Hello,

How we can setup builtin rest framework documentation features?
For example Browsable API. Overriding get_serializer in every APIView sounds boring.

Thank you

**Comment by RadoRado** [comment]
@DAKZH That's a great question.

We have the following mixin in some of our projects:

```
from rest_framework.schemas import AutoSchema


class ApiDocsMixin():
    schema = AutoSchema()

    def get_serializer(self):
        if hasattr(self, 'InputSerializer'):
            return self.InputSerializer()

        if hasattr(self, 'OutputSerializer'):
            return self.OutputSerializer()

```

This handles some basic cases, but it can be done quite better. Once we have resolutions there, we'll be adding examples.

Again, a general rule of thumb is - if you need to create a "framework-like" abstraction, to make your life easier, do so.

**Comment by RadoRado** [comment]
Closing this in favor of #82
