### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by RadoRado** [HackSoftware/Django-Styleguide#23]
Odin was a good example back then. Now it's deprecated.

**Comment by funkindy** [comment]
Hi, great guide! Does this mean that Odin repo is now not supposed to be the demo project of this style guide?

**Comment by RadoRado** [comment]
@funkindy Odin repo was the initial example project, but we no longer support it.

I'm currently working on a better example & due to Corona situation, we should have something available soon.

**Comment by carlosnasillo** [comment]
> @funkindy Odin repo was the initial example project, but we no longer support it.
> 
> I'm currently working on a better example & due to Corona situation, we should have something available soon.

This would be amazing @RadoRado 

Honestly I've been in tutorial hell in the past weeks, seeing with overly simple examples, with no attention to writing scalable software, let alone leveraging good design patterns. 

Came across your presentation on [EuroPython Conference](https://www.youtube.com/watch?v=yG3ZdxBb1oo) and it was fenomenal.

**Comment by RadoRado** [comment]
@carlosnasillo Sorry for the long-delayed response. We are actively running without any notifications.

This is the example project that we are currently working on - https://github.com/HackSoftware/Styleguide-Example

Should be updated each week with something small.

Until then, if you have a specific question, just open an issue here

**Comment by masdot** [comment]
Thank you very much for this styleguide. I really like your way of designing Django apps!

Could you please add an example of an UpdateAPI to the styleguide. I am learning Django and after many attempts I fail to write a correct service that updates a model.

**Comment by masdot** [comment]
@RadoRado should I leave my request here as a comment, or would it be better for you to open a new issue?
