### ISSUE TITLE
API example views return serializer instead of the serializer's data

### ISSUE THREAD

**Issue by knasti** [HackSoftware/Django-Styleguide#24]
Hey,

Awesome project, really helped me structure my code in a favorable manor.

I was mimicking the behavior of the List and Detail API views. It seems that they return the actual serializer instead of the serializer's.

![image](https://user-images.githubusercontent.com/21027620/67630751-d558fe80-f88c-11e9-8482-c8d8244e803d.png)

I did this:
![image](https://user-images.githubusercontent.com/21027620/67630772-19e49a00-f88d-11e9-9a40-e3ec66aeb673.png)

**Comment by RadoRado** [comment]
@knasti Ah, yes, we've missed that. Good catch :ok_hand: 

PR with fix is coming soon.

**Comment by wencakisa** [comment]
Resolved by https://github.com/HackSoftware/Django-Styleguide/pull/25

Thank you for opening the issue, @knasti .
