### ISSUE TITLE
API response structure

### ISSUE THREAD

**Issue by RadoRado** [HackSoftware/Django-Styleguide#31]
It's a good idea to add few words about how to structure API responses so they are consistent.

This also includes:

* Working with filters
* Pagination
* How to properly format error responses

**Comment by RTS340** [comment]
@RadoRado Do you have any examples of how pagination and filters are performed in your projects. 

Do you handle these within your selectors by passing arguments or do implement `GenericAPIView` so you can use the built in pagination and filtering mechanism and use your selectors within the `get_queryset`

cheers

**Comment by RadoRado** [comment]
@RTS340 Here's an example of a list API with filtering + pagination, matching the styleguide: https://github.com/HackSoftware/Styleguide-Example/pull/11

It's still work in progress (need to write tests), but the general idea is there.

**Comment by RadoRado** [comment]
This is 1/2 done now - https://github.com/HackSoftware/Django-Styleguide#filters--pagination

**Comment by RadoRado** [comment]
This is 2/2 done now - https://github.com/HackSoftware/Django-Styleguide#errors--exception-handling
