### ISSUE TITLE
Missing __init__ in models and selectors test directories

### ISSUE THREAD

**Issue by knasti** [HackSoftware/Django-Styleguide#32]
I was going over my tests as I want to move them to the structure you propose. In the picture you have there's no __ init __.py under models and selectors. I imagine this isn't intentional. At least my IDE (PyCharm) couldn't find the tests if __ init __.py isn't present. I know this is a tiny thing, but it had me tricked for a while.

![image](https://user-images.githubusercontent.com/21027620/68213377-be788180-ffdb-11e9-9ce6-0b7fb85371d6.png)

**Comment by wencakisa** [comment]
@knasti You're right.

We've missed that. I've just opened a PR which adds the missing files.

Thanks for contributing. :+1:
