### ISSUE TITLE
Instance or id arguments for services?

### ISSUE THREAD

**Issue by hgylfason** [HackSoftware/Django-Styleguide#34]
For services with arguments that represent model instances (e.g. ids) do you have a preference for whether to give the whole instance as argument or the instance's id? 

```
def update_user(
  *,
  user: User,
  group: UserGroup,
  name: str
) -> User:
  ...

# vs.

def update_user(
  *,
  user_id: int,
  group_id: int,
  name: str
) -> User:
  ...
```

**Comment by RadoRado** [comment]
@hgylfason That's a good question.

We have projects where we accept ids & fetch the object afterwards, and projects where we accept the instances. Depends on the context.

My personal preference is:

1. Always accept instance in the service.
2. Do `get_object_or_404` / use `PrimaryKeyRelatedField` in the API to obtain that instance.

Unless you have a good reason to do otherwise, I think that's a good default :+1:

**Comment by RadoRado** [comment]
Closing this for now :raised_hands:

**Comment by Atorich** [comment]
Why not to use something like:

```
def instance_or_id(*fields):
    """
    Service decorator. Makes possible to pass instance or its `id` as typehined argument.
    """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            if not fields:
                # consider we're need to handle ALL kwargs
                keys_to_retrieve = list(kwargs.keys())
            else:
                # specify fields to handle
                keys_to_retrieve = list(fields)

            to_retrieve = []
            real_kwargs = {}

            for key, value in kwargs.items():
                key_annotation = func.__annotations__.get(key)
                key_type = typing.get_args(func.__annotations__[key])[0] if key_annotation else None

                keep_as_is = any((
                    key not in keys_to_retrieve,
                    key_type is None,
                    not isinstance(key_type, models.Model),
                    not isinstance(value, int),
                ))
                if keep_as_is:
                    real_kwargs[key] = value
                    continue

                to_retrieve.append((key, key_type, value))

            for retrieve_tuple in to_retrieve:
                key, model, pk = retrieve_tuple
                real_kwargs[key] = model.objects.get(pk=pk)

            return func(*args, **real_kwargs)
        return wrapper
    return decorator
```


and the usage:

```
    @instance_or_id()
    def update_user(*, user: Union[User, int], newname: str):
        user.name = newname
        user.save()
        return user

        ```

**Comment by hgylfason** [comment]
I'd like to mention one benefit of using ID's.

Using an ID to reference a model limits its exposure beyond the application's boundaries. This is beneficial when you want model changes to be made through 'official interfaces,' like a service function. Passing only the model's ID, instead of the full instance, creates a (hopefully) high enough barrier for making changes directly to the model that you'll remember using the official interface.
