### ISSUE TITLE
Consider using django-stubs

### ISSUE THREAD

**Issue by sobolevn** [HackSoftware/Django-Styleguide#40]
Hi! Thanks for this awesome guide!

I see that you use type annotations with querysets and django.
I suggest to give https://github.com/typeddjango/django-stubs a try.

It support real QuerySet and model annotations. So, you won't use `-> Iterable[MyModel]` where `QuerySet[MyModel]` should be used.

**Comment by RadoRado** [comment]
That's a good idea. Will give it a try :+1:

**Comment by RadoRado** [comment]
This is going to be introduced to the example project: https://github.com/HackSoftware/Django-Styleguide-Example/issues/89

**Comment by RadoRado** [comment]
Updated the `mypy` :v:
