### ISSUE TITLE
inline_serializer in an OutputSerializer implementation

### ISSUE THREAD

**Issue by juanpsenn** [HackSoftware/Django-Styleguide#45]
I'am having troubles with the inline_serializer for an OutputSerializer, let's suppose i have the following models:

> class A(models.Model):
>   att_1=models.IntegerField()
>   model_b_reference=models.ForeignKey('B')
>    model_c_reference=models.ForeignKey('C')

> class B(models.Model):
>   att_1=models.IntegerField()
>   att_2=models.IntegerField()

> class C(models.Model):
>   att_1=models.IntegerField()
>   att_2=models.IntegerField()

How can i implement an OutputSerializer if i want to show in depth attributes from B model and not C; here it is an example of a desired json response for class A serializer:
`{
   "att_1":1,
   "model_b_reference":{
      "att_1":1,
      "att_2":2
   },
   "model_c_reference":1
}`

**Comment by pgergov** [comment]
Hello @juanpsenn :wave: 

Here's how you can achieve the desired result:

```python
class OutputSerializer(serializers.Serializer):
    att_1 = serializers.IntegerField()
    model_b_reference = inline_serializer(
        fields={
            'att_1': serializers.IntegerField(),
            'att_2': serializers.IntegerField()
        }
    )
    model_c_reference = serializers.IntegerField(source='model_c_reference.id')
```

Please follow up if this solution works for you or if you have any other questions :beers:

**Comment by juanpsenn** [comment]
Yeah that's exactly what I've been looking for! Thanks you very much!
