### ISSUE TITLE
Nullable URL fields?

### ISSUE THREAD

**Issue by akx** [HackSoftware/Django-Styleguide#49]
Why are some of the URLs in the example model `null=True`, while others are not?

```
    repository = models.URLField(blank=True)
    video_channel = models.URLField(blank=True, null=True)
    facebook_group = models.URLField(blank=True, null=True)
```

After all, in general it's considered bad practice to have string fields with two distinct falsy values (`''` and `None` for a nullable string) unless being able to differentiate between "no value set" and "empty value set" is a business requirement, or there's an uniqueness constraint on the field.

**Comment by wencakisa** [comment]
Hi, @akx !

You're right, setting both `blank` & `null` to `True` on `CharField` and its derived classes is not considered a good practice.

We're actually using it as stated in [**Two Scoops of Django**](https://www.feldroy.com/products/two-scoops-of-django-1-11):
![](https://i.stack.imgur.com/TMMej.png)
![](https://i.stack.imgur.com/gUanA.png)

Thanks for noticing this in our guide, we'll change this right away!

Cheers! :raised_hands:
