### ISSUE TITLE
Celery schedule objects

### ISSUE THREAD

**Issue by psmolak** [HackSoftware/Django-Styleguide#52]
According to https://django-celery-beat.readthedocs.io/en/latest/ if we have multiple periodic tasks executing i.e every 10 sec, then they should all point to the same schedule object. Inside the source code of `setup_periodic_tasks.py`, we create new schedule object each time using `.create` instead of `get_or_create`.

Not sure if this has any significance on beat scheduler correctness but decided to make an issue here on Github anyway.

**Comment by RadoRado** [comment]
@psmolak That's actually a good catch.

To be honest, we haven't used anything outside a cron schedule & we haven't got any problems with different schedule objects that contain the same cron.

But I'll add a reference to the Celery documentation there, so people can pay attention.

Cheers!

**Comment by RadoRado** [comment]
Added - https://github.com/HackSoftware/Django-Styleguide/commit/c63b60ff7dac791d3e68703c4587fa86858d5602

Thanks again & sorry for the late response.
