### ISSUE TITLE
Why does the functions have an unused * arg?

### ISSUE THREAD

**Issue by whatseria** [HackSoftware/Django-Styleguide#55]
Sorry about the dumb question, I couldn't find an answer.

Example:
```python
def get_users(*, fetched_by: User) -> Iterable[User]:
    user_ids = get_visible_users_for(user=fetched_by)

    query = Q(id__in=user_ids)

    return User.objects.filter(query)
```

**Comment by wencakisa** [comment]
In Python, the `*` arg means:

> All following arguments **must be** passed as keyword-only arguments, not as positional arguments

For example, you **can** call the function like:

```python
get_users(fetched_by=user)  # keyword argument
```

but you **cannot** call it like:

```python
get_users(user)  # positional argument
```

Here's the official Python documentation for this: https://www.python.org/dev/peps/pep-3102

:v:
