### ISSUE TITLE
How to handle pagination, filtering and ordering

### ISSUE THREAD

**Issue by RTS340** [HackSoftware/Django-Styleguide#59]
In my current project I have used selectors as defined in the guide.

I was wondering how you have implemented pagination, filtering and ordering. Normally when using rest framework this is done within the api by using the ListModelMixin, which under the hood will perform these on the queryset provided.

Do you handle these within your service instead or do implement a mechanism in the API like ListModelMixin. By leaving the services more generic and let the calling code handle these against a queryset returned by a selector.

Cheers

**Comment by RadoRado** [comment]
@RTS340 Yep, we have some specific ways of handling it. It should end up in the https://github.com/HackSoftware/Styleguide-Example at some point

**Comment by thommor** [comment]
Can you give us a clue on how you're handling it?

**Comment by RadoRado** [comment]
@RTS340 @thommor 

@RTS340 Here's an example of a list API with filtering + pagination, matching the styleguide: https://github.com/HackSoftware/Styleguide-Example/pull/11

It's still work in progress (need to write tests), but the general idea is there.

**Comment by RadoRado** [comment]
Okay, now the styleguide itself is updated  - https://github.com/HackSoftware/Django-Styleguide#filters--pagination

Closing this issue :vulcan_salute:
