### ISSUE TITLE
Exception handling and nested serializer with many=True

### ISSUE THREAD

**Issue by aesfur** [HackSoftware/Django-Styleguide#60]
There are the following serializers:

```
class ItemSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    count = serializers.DecimalField(max_digits=12, decimal_places=2)
    is_removed = serializers.BooleanField()


class DocumentSerializer(serializers.Serializer):
    comment = serializers.CharField()
    items = ItemSerializer(many=True, required=True, allow_empty=False)
```
Or

```
class DocumentSerializer(serializers.Serializer):
    comment = serializers.CharField()
    items = inline_serializer(many=True, fields={
        'id': serializers.IntegerField(),
        'count': serializers.DecimalField(max_digits=12, decimal_places=2),
        'is_removed': serializers.BooleanField()
    })
```

I expected the following error formatting on an invalid request:
```
{
    "errors": [
        {
            "message": "This field is required.",
            "code": "required",
            "field": "items.0.is_removed"
        },
        {
            "message": "This field is required.",
            "code": "required",
            "field": "items.1.is_removed"
        }
    ]
}
```
But I got:
```
{
    "errors": [
        {
            "is_removed": [
                {
                    "message": "This field is required.",
                    "code": "required"
                }
            ],
            "field": "items"
        },
        {
            "is_removed": [
                {
                    "message": "This field is required.",
                    "code": "required"
                }
            ],
            "field": "items"
        }
    ]
}
```
What's wrong? thanks

**Comment by wencakisa** [comment]
Hi, @aesfur !

Your serializers' structure looks valid, but it seems that you're not using the [`ErrorsFormatter`](https://github.com/HackSoftware/Django-Styleguide/blob/d1cf996a5e97f825f59010c16f69945ef3600d56/utils.py#L67), documented in the [Error formatting section](https://github.com/HackSoftware/Django-Styleguide#error-formatting).

This, combined with the mechanism explained in the [API exception handling section](https://github.com/HackSoftware/Django-Styleguide#handle-exceptions-in-apis) is the solution of your problem.

Cheers! :raised_hands:

**Comment by aesfur** [comment]
@wencakisa Hi!

I use the [formatter](https://github.com/HackSoftware/Styleguide-Example/blob/2f82daf28d7d3ed3d454adf33c528f6bf9b09c4e/styleguide_example/api/errors.py#L37) from example. 
But the examples above are not formatted correctly

 Only this works as expected:
`items = serializers.ListField(child=ItemSerializer())`
