### ISSUE TITLE
Error response when raising non field validation errors

### ISSUE THREAD

**Issue by RTS340** [HackSoftware/Django-Styleguide#61]
Through using the guide I have implemented some model specific validation as recommended. I.e. 

```
def clean(self):
        if self.start_date > self.end_date:
            raise ValidationError("End date cannot be before start date!")
```

After setting up the custom Exception Handling and Error Formatting I have noticed the output won't be:

```
{
  "errors": [
    {
      "message": "End date cannot be before start date!",
      "code": "Invalid",
    }
    ]
}
```

But instead:

```
{
  "errors": [
    {
      "message": "End date cannot be before start date!",
      "code": "Invalid",
      "field": "__all__",
    }
    ]
}
```

I assume that the field should be removed from the response if the validation is a non field error?

If this is the case it is down to `key_is_non_field_errors = key == api_settings.NON_FIELD_ERRORS_KEY` inside of the ErrorsFormatter class. The default key for DRF is `non_field_errors` where as the default django validation error key (NON_FIELD_ERRORS) is `__all__`.

To remove the field name from the response when it is a non field error I have implemented the following :

```
from django.core.exceptions import NON_FIELD_ERRORS as DJANGO_NON_FIELD_ERRORS_KEY

key_is_non_field_errors = key in [
                api_settings.NON_FIELD_ERRORS_KEY,
                DJANGO_NON_FIELD_ERRORS_KEY,
            ]
```

If this was not the intended behaviour then please ignore the above.

Cheers.

**Comment by RadoRado** [comment]
@RTS340 Thanks for opening this.

The errors formatter needs a revisit from us.

That's why we started the https://github.com/HackSoftware/Styleguide-Example project, where the error formatter can be covered with tests && reworked to something more readable.

This kind of error, we usually treat as "General error" and if it's tied to a form, we display this someone central, instead next to the field.

If you want to raise that error for a specific field, you can do the following:

```python
raise ValidationError({'start_date': 'End date cannot be before start date!'})
```

There are tests for that here - https://github.com/HackSoftware/Styleguide-Example/blob/master/styleguide_example/api/tests/errors/test_error_formatter.py#L55

**Comment by RTS340** [comment]
Thanks for the reply.

Raising field related errors works perfect and the formatting works as expected.

When raising a validation error from within the api like in your tests (https://github.com/HackSoftware/Styleguide-Example/blob/master/styleguide_example/api/tests/mixins/test_api_errors_mixin.py#L12), it responds with the correct output:

```
{
            'errors': [{
                'message': 'Some error',
                'code': 'error'
            }]
}
```

But when raising a 'general error' from within the clean method from within the models:
```
def clean(self):
    raise ValidationError('test')
```

The error will be formatted like so with the current implementation:

```
{'errors': [{'message': 'test', 'code': 'invalid', 'field': '__all__'}]}
```

**Comment by RadoRado** [comment]
@RTS340 This may be really late, but if you do:

```python
raise ValidationError({"field": "test"})
```

you might end up with the proper formatting.

Cheers!

**Comment by RadoRado** [comment]
Closing this for now :v:

**Comment by Dsantacruz** [comment]
> @RTS340 This may be really late, but if you do:
> 
> ```python
> raise ValidationError({"field": "test"})
> ```
> 
> you might end up with the proper formatting.
> 
> Cheers!

This worked for me, custom message for only field.
