### ISSUE TITLE
How and Where to add Permissions?

### ISSUE THREAD

**Issue by charanjit-singh** [HackSoftware/Django-Styleguide#66]
For Eg:
We have permission: 
Only user can access to this resource, where and how to create the permission: `can_access_resource(user)`?

Currently, I am doing it in selectors it returns true or false and depending on that I raise an exception in Services.

**Comment by RadoRado** [comment]
@charanjit-singh Hello :wave: 

Permissions are also part of the "business logic", so you can handle them via services & selectors.

Even if you decide to use Django's permission system, you can import the correct models & implement a layer around them.

Quick example for an approach:

* Introduce a `permissions` app
* Introduce `user_has_permission` service, for example
* Implement it however it's suitable for you
* Whenever you need to do an action that requires permission - pass `user` to the service/selector & call `user_has_permission`
* You can either raise some kind of exception, that's handled by the API layer, to return an appropriate response
* Or you can implement it however suits you best

That's the general idea.  Treat permissions as if they are another part of your application/business logic (they are)

Cheers!

**Comment by RadoRado** [comment]
Closing this for now :raised_hands:
