### ISSUE TITLE
Add section for basic principles when working with Celery

### ISSUE THREAD

**Issue by RadoRado** [HackSoftware/Django-Styleguide#7]

**Comment by knasti** [comment]
I am in doubt on how to structure the Celery parts of my project in a good way, this would be an awesome addition.

**Comment by RadoRado** [comment]
@knasti I've pushed an initial Celery section: https://github.com/HackSoftware/Django-Styleguide#celery

Would love to hear feedback from you & also - what else do you want to see / ask :thinking:

**Comment by knasti** [comment]
I love it, and your style guide is very valuable to me. It makes me feel in control of my code, which in return makes it much more pleasant to code and add features to my projects. 

I can't think of anything to add to the style guide off the top of my head, but I did wonder what your take is on using keywords in Django's ValidationErrors. In my project I added "status_code" to my body of exception handling like shown on the picture, but that only works if I add the keyword message to the ValidationError (thus creating a dict like response body).

![image](https://user-images.githubusercontent.com/21027620/68087768-eab7c500-fe58-11e9-9c67-52f5d03063af.png)

raise ValidationError("Something does not exist")
raise ValidationError(message={"something": "Something does not exist"})

**Comment by RadoRado** [comment]
@knasti That's an important topic. DRF handles those errors quite specifically and usually every project needs a custom way of structuring the error responses.

We have a large chunk of code to handle this, but it's currently untested & quite messy (although - working pretty good)

I'll open another issues about that and try to push something.

As for the particular question - not sure why this is the behavior. The best thing you can do is to read thru `ValidationError` code & also the exception handling in the `APIView` from DRF :+1:

**Comment by knasti** [comment]
@RadoRado I have been thinking on a couple of things that could be mentioned. I'm not sure it belongs in a StyleGuide, but I'll give it a go, and then you can help evaluating if it belongs or not.

 - Signals (When to use them and where to place them)
 - Middleware (When to use, and where to place them)

Also, I can see that you use a customized Object Manager in the Course class, what do you use that for? Should methods in a customized Object Manager not go to "selectors" or "services"? (pic from django docs on customized Object Managers)

![image](https://user-images.githubusercontent.com/21027620/68379236-cc4e1400-014d-11ea-9f14-b8b175b6d208.png)

Lastly you mention that you write tests for APIs and views (see picture), but do not give any examples on such tests, would be cool if an example could be added.

![image](https://user-images.githubusercontent.com/21027620/68379624-85145300-014e-11ea-8a53-93b43f575218.png)

Looking forward to hear your opinion on the above.

**Comment by RadoRado** [comment]
@knasti Adding examples for signals & middlewares is a good idea. Will open issues for that.

Tests for API / views also.

About custom managers, I'm a bit on the fence for that. There's a case where you can achieve the same thing with class/static methods & custom managers / querysets & everything would look great.

For me, a manager has a 1:1 relation to the ORM object & if I don''t want to inflate the ORM object with business logic, the same thing applies for the manager.

The examples with the `Course` class are a bit outdated. We need to push some effort for #23 and provide a more up to date example.

**Comment by RadoRado** [comment]
This can now be considered as done - https://github.com/HackSoftware/Django-Styleguide#celery
