### ISSUE TITLE
Why i have to use drf APIs with nested serializer?

### ISSUE THREAD

**Issue by thomas545** [HackSoftware/Django-Styleguide#78]
if I used a nested serializer in API views is that doesn't bad for performance, code design, and clean code approach ??!!

**Comment by RadoRado** [comment]
@thomas545 Hello :wave: 

You need nested serializers when you have nested data, that you want to serialize. This does not necessarily impact performance (unless you start making N+1 queries in the nesting).

Otherwise, about your approach, it sounds reasonable to me. If you can elaborate more, with an example, I can be more helpful.

Cheers :v:

**Comment by thomas545** [comment]
@RadoRado Thanks for your interest and response.

My approach that I mean, I want to make serializer in `serializer.py` file with unique serializer name
and call it in views like:

-> serializer.py
`
class CreateUserSerializer(serializers.Serializer):
`
`
    username = serializers.CharField()
    email = serializers.CharField()
    ....
`

-> views.py
`
from app.serializers import CreateUserSerializer

class CreateUserAPI(generics.GenericAPIView):
    serializer_class = CreateUserSerializer
`


So I don't want to do your approach in APIs

`
class CourseCreateApi(SomeAuthenticationMixin, APIView):
    class InputSerializer(serializers.Serializer):
        name = serializers.CharField()
        start_date = serializers.DateField()
        end_date = serializers.DateField()

    def post(self, request):
        serializer = self.InputSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        create_course(**serializer.validated_data)

        return Response(status=status.HTTP_201_CREATED)
`

**Comment by RadoRado** [comment]
@thomas545 If the approach that you presented suits you & your team better, you should use it.

What we've suggested in the styleguide is something that works well for us.

Cheers :v:

**Comment by thomas545** [comment]
@RadoRado 

> What we've suggested in the styleguide is something that works well for us.
My question is:
Does this affect performance or clean code approach?

Cheers

**Comment by kdkocev** [comment]
Note that using an inline serializer is useful when that serializer is only used to parse, validate or serialize data.
If you want to change or create data in the database (like the CreateUserSerializer is likely doing) you should use a serializer that is not for code separation concerns.

The logic that does changes to the database, or gets data from the database (the business logic) is extracted into `services`, so the serializers are not used for anything other than parsing, serializing and validating data.

As a bonus, extracting the business logic outside of the API/Serializer layer into a function (`service`), makes it even easier to unit test. :v:

**Comment by thomas545** [comment]
I got it, Thank you very much

**Comment by RadoRado** [comment]
Closing this for now :raised_hands:
