### ISSUE TITLE
Creation services with many fields in the model

### ISSUE THREAD

**Issue by jsandovalc** [HackSoftware/Django-Styleguide#79]
Hi everyone,

I noticed that for updating, it's recommended to use a data dict with the fields to update (https://github.com/HackSoftware/Django-Styleguide/issues/57). I was wondering if you do something similar with creates. I have a creation service with a lot of fields, and it the method signature gets really long.

Do you do something similar to updates?

Thanks.

**Comment by RadoRado** [comment]
@jsandovalc Hello :wave: 

If it makes sense to pass a data dictionary for something that needs to create an object with a lot of fields - do so.

The general rule of thumb is to have a strictly-defined list of possible fields, so you don't just do:

```python
for key, value in data.items():
    setattr(obj, key, value)
```

but rather:

```python
for key in possible_fields:
    if key in data:
        value = data[key]
        setattr(obj, key, value)
```

**Comment by RadoRado** [comment]
Closing for now :v:
