### ISSUE TITLE
Update service

### ISSUE THREAD

**Issue by RadoRado** [HackSoftware/Django-Styleguide#85]
Add an example for an update service.

Can also use this - <https://docs.djangoproject.com/en/3.2/ref/models/instances/#specifying-which-fields-to-save>

**Comment by farzeni** [comment]
Hi,

The most obscure thing I'm facing about updates is how to structure services arguments to handle partial updates.

Following the create approach
```
def todo_update(*, text: str, completed: bool):
   # do update
```
makes it  mandatory to update all fields each time

instead using something like
```
def todo_update(*, data: dict):
   # do update with **dict
``

it lose code completion and all the good things that come using named parameters.

any good advise?

**Comment by RadoRado** [comment]
@farzeni Thanks for reaching out :raised_hands: 

We are currently working on this particular thing and will provide examples once it's done.

**Comment by wencakisa** [comment]
Resolved with #92 ✅

**Comment by RadoRado** [comment]
@farzeni Does this actually answer your question / solve your issue: https://github.com/HackSoftware/Django-Styleguide#handling-updates-with-a-service :thinking:

**Comment by RadoRado** [comment]
I think we can also improve with M2M support.

We can adapt this:

```python
def update_model_fields(
    *,
    model_instance,
    data,
    clean_instance=True
):
    m2m_data = {}

    for field_name, value in data.items():
        try:
            field = model_instance._meta.get_field(field_name)
        except FieldDoesNotExist as exc:
            raise ValidationError(str(exc))

        if isinstance(field, ManyToManyField):
            m2m_data[field_name] = value

            continue

        setattr(model_instance, field_name, value)

    if clean_instance:
        model_instance.full_clean()

    model_instance.save()

    for field_name, value in m2m_data.items():
        related_manager = getattr(model_instance, field_name)
        related_manager.set(value)

    return model_instance
 ```

**Comment by cbows** [comment]
Hi @p02diada, I wanted to use a single `data` dictionary as the input to my update service, but still have good developer experience like you. Right now I am using `TypedDict`s to specify types for the input to my update services. After validation using the DRF serializers I cast the `request.data` to the proper type and pass it to the update service. I describe the approach in #103. Typed dicts can have fields that are [NotRequired](https://peps.python.org/pep-0655/) (available in `typing_extensions` as an alternative to `total=False`) which makes it simple to declare fields that can be missing. Your LSP or static type checker can then warn you that `data['not_required_field']` is unsafe so you should use something like `data.get('not_required_field', MISSING)` as a safe accessor. Having a typed dictionary also provides you with auto-completion of keys and other good stuff.

**Comment by RadoRado** [comment]
Hello,

With the following updates:

- https://github.com/HackSoftware/Django-Styleguide-Example/pull/305
- https://github.com/HackSoftware/Django-Styleguide/commit/bac4059efd9d52a098ea731d8f7d45a2a559fb84

I'm considering this issue for closed 🙌

Of course, if anyone has any questions, feel free to reopen it / open another issue / post in discussions.

Cheers!
