### ISSUE TITLE
Create and validate two models with a relationship between them at the same time

### ISSUE THREAD

**Issue by MohamedAliHamza** [HackSoftware/Django-Styleguide#94]
Hi there! would like to thank you for sharing this info with us 👋

I'm trying to apply the pattern in my projects but there is a case I need your help in.

Let's take an example that exists in the repo, 
```python
def user_create(
    *,
    email: str,
    name: str
) -> User:
    user = User(email=email)
    user.full_clean()
    user.save()

    profile_create(user=user, name=name)
    confirmation_email_send(user=user)

    return user
```
As you said earlier this method creates a new `User` model and call another service `profile_create`

Let's say there are other fields in the `Profile` model I need to validate and assume there is a problem in this data like phone number is wrong so I need to raise an exception with that error, the problem here has we already created a `User` object without creating a `Profile` so we need to delete this user from the `DB` and this would hit the `DB` for creating and deleting.

We need to check if all data are valid, then create the models. Based on this problem I couldn't apply your pattern so do you suggest any thoughts about how can I solve this issue? I thought about `synchronization` but I'm not familiar with it yet!

**Comment by RadoRado** [comment]
@MohamedAliHamza :wave: 

A couple of things:

1. You'd like to use atomic transactions for your services (more on that, here - https://docs.djangoproject.com/en/4.0/topics/db/transactions/)
2. If you need to clean your data, you can do that separately (either via serializers or via something like `user_create_clean`) that can raise an exception (how you handle exceptions is up to you. Here are our recommendations - https://github.com/HackSoftware/Django-Styleguide#errors--exception-handling
3. The `profile_create` service might also have a `.full_clean()`, which will raise error and will revert the transaction.

Do let me know if you have follow-up questions :raised_hands:

**Comment by MohamedAliHamza** [comment]
1- I thought about `atomic transactions` but it's not a good solution when traffic increases.

2- That's an available option, assume I put it inside `user_create_clean` and if all conditions are passed, then create the model, but in this case, I don't have to create another services `user_create` to just create an object, right?
the `API` in this case could be  maybe something like that:
``` python
class CreateUserApi(APIView):
    def post(self, request):
        serializer =  CreateUserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        # user_create_clean()
        # profile_create_clean()
        # user = User.object.create(..) 
        # profile = Profile.object.create(user=user, ..) 
        return Response(status=status.HTTP_201_CREATED)   
```

**Comment by RadoRado** [comment]
@MohamedAliHamza If using transactions is not an option, then no matter how you structure your code, you'll be vulnerable to the scenario where 1 objects get created and the other does not.

The best you can do in that scenario is to invest heavily in application-layer validation on your data & cover that with tests.

That said, it's best to use transactions. If scale is an issue, you can address that scale in various other ways.

Cheers!

**Comment by MohamedAliHamza** [comment]
Thanks @RadoRado I appreciate your help, have a nice day 🙌

**Comment by RadoRado** [comment]
@MohamedAliHamza Cheers :raised_hands:
