### ISSUE TITLE
How to generate OpenAPI schema?

### ISSUE THREAD

**Issue by charanjit-singh** [HackSoftware/Django-Styleguide#97]
How to generate OpenAPI schema if we're using `InputSerializer` or `OutputSerializer`? 

I believe there should be a common `serializers` folder that can be used to define [OpenApi Schemas](https://swagger.io/docs/specification/data-models/)

**Comment by RadoRado** [comment]
@charanjit-singh Hello :wave: 

If you want to automatically generate OpenAPI schema from the defined APIs, you need to check what the popular libraries are looking for and just add those missing methods to the APIs (can be done via mixin). It's usually things like `get_serializer_class` that need to be defined.

Can you point me to the library that you are using?

Aside from that, from our experience, automatic schema generation never worked well. What we usually do is to just write our OpenAPI schema by hand.

Cheers!

**Comment by RadoRado** [comment]
@charanjit-singh I'm closing this for now. Feel free to reopen or open a new issue if you have other questions.

**Comment by akhil023** [comment]
Could you please elaborate on writing OpenAPI schema by hand? Could not find about it in the style guide
